theme: jekyll-theme-cayman

# Exclude these pages from the visible website
exclude: [".rvmrc", ".rbenv-version", "ReadMe.md", "Rakefile", "changelog.md", "License.md"]

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title : Nathan Hahn
author :
  name : Nathan Hahn
  email : nhahn@resolv.org
  github : nathanrhahn
  twitter : @nathanrhahn
  feedburner : nil

# NOTE: If replacing this next line with your own URL, you likely want "https://" not "http://"
production_url : https://nathanrhahn.github.io/
